spring:
  application:
    name: service2
    
server:
  port: 8302
 
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8300/eureka/
  instance:
    hostname: localhost